name: Auto Update JSON

on:
  workflow_dispatch:
  # schedule:
  #   # - cron: "*/5 * * * *"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_json.py

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin git@github.com:mindfullMellow/My-Crypto-Portfolio.git
          git add public/top_500_assets.json
          if ! git diff --staged --quiet; then
            git commit -m "auto updating json"
            git push origin main
          else
            echo "No changes to commit"
          fi
