name: Auto Update JSON
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_json.py
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/top_500_assets.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto updating json"
            git push origin main
          fi
